export enum EventType {
  COMPETITION_CREATED = 'competition-created',
  COMPETITION_ENDED = 'competition-ended',
  COMPETITION_ENDING = 'competition-ending',
  COMPETITION_PARTICIPANTS_JOINED = 'competition-participants-joined',
  COMPETITION_STARTED = 'competition-started',
  COMPETITION_STARTING = 'competition-starting',
  GROUP_CREATED = 'group-created',
  GROUP_MEMBERS_JOINED = 'group-members-joined',
  GROUP_MEMBERS_LEFT = 'group-members-left',
  GROUP_MEMBERS_ROLES_CHANGED = 'group-members-roles-changed',
  GROUP_UPDATED = 'group-updated',
  NAME_CHANGE_CREATED = 'name-change-created',
  PLAYER_ACHIEVEMENTS_CREATED = 'player-achievements-created',
  PLAYER_ARCHIVED = 'player-archived',
  PLAYER_DELTA_UPDATED = 'player-delta-updated',
  PLAYER_FLAGGED = 'player-flagged',
  PLAYER_NAME_CHANGED = 'player-name-changed',
  PLAYER_TYPE_CHANGED = 'player-type-changed',
  PLAYER_UPDATED = 'player-updated'
}
