import { Country } from '@prisma/client';

export interface CountryDetails {
  code: Country;
  name: string;
}

type CountryPropsMap = {
  [c in Country]: CountryDetails;
};

const CountryProps: CountryPropsMap = {
  [Country.AD]: { code: 'AD', name: 'Andorra' },
  [Country.AE]: { code: 'AE', name: 'United Arab Emirates' },
  [Country.AF]: { code: 'AF', name: 'Afghanistan' },
  [Country.AG]: { code: 'AG', name: 'Antigua and Barbuda' },
  [Country.AI]: { code: 'AI', name: 'Anguilla' },
  [Country.AL]: { code: 'AL', name: 'Albania' },
  [Country.AM]: { code: 'AM', name: 'Armenia' },
  [Country.AO]: { code: 'AO', name: 'Angola' },
  [Country.AQ]: { code: 'AQ', name: 'Antarctica' },
  [Country.AR]: { code: 'AR', name: 'Argentina' },
  [Country.AS]: { code: 'AS', name: 'American Samoa' },
  [Country.AT]: { code: 'AT', name: 'Austria' },
  [Country.AU]: { code: 'AU', name: 'Australia' },
  [Country.AW]: { code: 'AW', name: 'Aruba' },
  [Country.AX]: { code: 'AX', name: 'Åland Islands' },
  [Country.AZ]: { code: 'AZ', name: 'Azerbaijan' },
  [Country.BA]: { code: 'BA', name: 'Bosnia and Herzegovina' },
  [Country.BB]: { code: 'BB', name: 'Barbados' },
  [Country.BD]: { code: 'BD', name: 'Bangladesh' },
  [Country.BE]: { code: 'BE', name: 'Belgium' },
  [Country.BF]: { code: 'BF', name: 'Burkina Faso' },
  [Country.BG]: { code: 'BG', name: 'Bulgaria' },
  [Country.BH]: { code: 'BH', name: 'Bahrain' },
  [Country.BI]: { code: 'BI', name: 'Burundi' },
  [Country.BJ]: { code: 'BJ', name: 'Benin' },
  [Country.BL]: { code: 'BL', name: 'Saint Barthélemy' },
  [Country.BM]: { code: 'BM', name: 'Bermuda' },
  [Country.BN]: { code: 'BN', name: 'Brunei Darussalam' },
  [Country.BO]: { code: 'BO', name: 'Bolivia' },
  [Country.BQ]: { code: 'BQ', name: 'Bonaire' },
  [Country.BR]: { code: 'BR', name: 'Brazil' },
  [Country.BS]: { code: 'BS', name: 'Bahamas' },
  [Country.BT]: { code: 'BT', name: 'Bhutan' },
  [Country.BV]: { code: 'BV', name: 'Bouvet Island' },
  [Country.BW]: { code: 'BW', name: 'Botswana' },
  [Country.BY]: { code: 'BY', name: 'Belarus' },
  [Country.BZ]: { code: 'BZ', name: 'Belize' },
  [Country.CA]: { code: 'CA', name: 'Canada' },
  [Country.CC]: { code: 'CC', name: 'Cocos (Keeling) Islands' },
  [Country.CD]: { code: 'CD', name: 'Congo' },
  [Country.CF]: { code: 'CF', name: 'Central African Republic' },
  [Country.CG]: { code: 'CG', name: 'Congo' },
  [Country.CH]: { code: 'CH', name: 'Switzerland' },
  [Country.CI]: { code: 'CI', name: "Côte d'Ivoire" },
  [Country.CK]: { code: 'CK', name: 'Cook Islands' },
  [Country.CL]: { code: 'CL', name: 'Chile' },
  [Country.CM]: { code: 'CM', name: 'Cameroon' },
  [Country.CN]: { code: 'CN', name: 'China' },
  [Country.CO]: { code: 'CO', name: 'Colombia' },
  [Country.CR]: { code: 'CR', name: 'Costa Rica' },
  [Country.CU]: { code: 'CU', name: 'Cuba' },
  [Country.CV]: { code: 'CV', name: 'Cabo Verde' },
  [Country.CW]: { code: 'CW', name: 'Curaçao' },
  [Country.CX]: { code: 'CX', name: 'Christmas Island' },
  [Country.CY]: { code: 'CY', name: 'Cyprus' },
  [Country.CZ]: { code: 'CZ', name: 'Czechia' },
  [Country.DE]: { code: 'DE', name: 'Germany' },
  [Country.DJ]: { code: 'DJ', name: 'Djibouti' },
  [Country.DK]: { code: 'DK', name: 'Denmark' },
  [Country.DM]: { code: 'DM', name: 'Dominica' },
  [Country.DO]: { code: 'DO', name: 'Dominican Republic' },
  [Country.DZ]: { code: 'DZ', name: 'Algeria' },
  [Country.EC]: { code: 'EC', name: 'Ecuador' },
  [Country.EE]: { code: 'EE', name: 'Estonia' },
  [Country.EG]: { code: 'EG', name: 'Egypt' },
  [Country.EH]: { code: 'EH', name: 'Western Sahara' },
  [Country.ER]: { code: 'ER', name: 'Eritrea' },
  [Country.ES]: { code: 'ES', name: 'Spain' },
  [Country.ET]: { code: 'ET', name: 'Ethiopia' },
  [Country.FI]: { code: 'FI', name: 'Finland' },
  [Country.FJ]: { code: 'FJ', name: 'Fiji' },
  [Country.FK]: { code: 'FK', name: 'Falkland Islands (Malvinas)' },
  [Country.FM]: { code: 'FM', name: 'Micronesia (Federated States of)' },
  [Country.FO]: { code: 'FO', name: 'Faroe Islands' },
  [Country.FR]: { code: 'FR', name: 'France' },
  [Country.GA]: { code: 'GA', name: 'Gabon' },
  [Country.GB]: { code: 'GB', name: 'United Kingdom' },
  [Country.GD]: { code: 'GD', name: 'Grenada' },
  [Country.GE]: { code: 'GE', name: 'Georgia' },
  [Country.GF]: { code: 'GF', name: 'French Guiana' },
  [Country.GG]: { code: 'GG', name: 'Guernsey' },
  [Country.GH]: { code: 'GH', name: 'Ghana' },
  [Country.GI]: { code: 'GI', name: 'Gibraltar' },
  [Country.GL]: { code: 'GL', name: 'Greenland' },
  [Country.GM]: { code: 'GM', name: 'Gambia' },
  [Country.GN]: { code: 'GN', name: 'Guinea' },
  [Country.GP]: { code: 'GP', name: 'Guadeloupe' },
  [Country.GQ]: { code: 'GQ', name: 'Equatorial Guinea' },
  [Country.GR]: { code: 'GR', name: 'Greece' },
  [Country.GS]: { code: 'GS', name: 'South Georgia and the South Sandwich Islands' },
  [Country.GT]: { code: 'GT', name: 'Guatemala' },
  [Country.GU]: { code: 'GU', name: 'Guam' },
  [Country.GW]: { code: 'GW', name: 'Guinea-Bissau' },
  [Country.GY]: { code: 'GY', name: 'Guyana' },
  [Country.HK]: { code: 'HK', name: 'Hong Kong' },
  [Country.HM]: { code: 'HM', name: 'Heard Island and McDonald Islands' },
  [Country.HN]: { code: 'HN', name: 'Honduras' },
  [Country.HR]: { code: 'HR', name: 'Croatia' },
  [Country.HT]: { code: 'HT', name: 'Haiti' },
  [Country.HU]: { code: 'HU', name: 'Hungary' },
  [Country.ID]: { code: 'ID', name: 'Indonesia' },
  [Country.IE]: { code: 'IE', name: 'Ireland' },
  [Country.IL]: { code: 'IL', name: 'Israel' },
  [Country.IM]: { code: 'IM', name: 'Isle of Man' },
  [Country.IN]: { code: 'IN', name: 'India' },
  [Country.IO]: { code: 'IO', name: 'British Indian Ocean Territory' },
  [Country.IQ]: { code: 'IQ', name: 'Iraq' },
  [Country.IR]: { code: 'IR', name: 'Iran (Islamic Republic of)' },
  [Country.IS]: { code: 'IS', name: 'Iceland' },
  [Country.IT]: { code: 'IT', name: 'Italy' },
  [Country.JE]: { code: 'JE', name: 'Jersey' },
  [Country.JM]: { code: 'JM', name: 'Jamaica' },
  [Country.JO]: { code: 'JO', name: 'Jordan' },
  [Country.JP]: { code: 'JP', name: 'Japan' },
  [Country.KE]: { code: 'KE', name: 'Kenya' },
  [Country.KG]: { code: 'KG', name: 'Kyrgyzstan' },
  [Country.KH]: { code: 'KH', name: 'Cambodia' },
  [Country.KI]: { code: 'KI', name: 'Kiribati' },
  [Country.KM]: { code: 'KM', name: 'Comoros' },
  [Country.KN]: { code: 'KN', name: 'Saint Kitts and Nevis' },
  [Country.KP]: { code: 'KP', name: "Korea (Democratic People's Republic of)" },
  [Country.KR]: { code: 'KR', name: 'Korea' },
  [Country.KW]: { code: 'KW', name: 'Kuwait' },
  [Country.KY]: { code: 'KY', name: 'Cayman Islands' },
  [Country.KZ]: { code: 'KZ', name: 'Kazakhstan' },
  [Country.LA]: { code: 'LA', name: "Lao People's Democratic Republic" },
  [Country.LB]: { code: 'LB', name: 'Lebanon' },
  [Country.LC]: { code: 'LC', name: 'Saint Lucia' },
  [Country.LI]: { code: 'LI', name: 'Liechtenstein' },
  [Country.LK]: { code: 'LK', name: 'Sri Lanka' },
  [Country.LR]: { code: 'LR', name: 'Liberia' },
  [Country.LS]: { code: 'LS', name: 'Lesotho' },
  [Country.LT]: { code: 'LT', name: 'Lithuania' },
  [Country.LU]: { code: 'LU', name: 'Luxembourg' },
  [Country.LV]: { code: 'LV', name: 'Latvia' },
  [Country.LY]: { code: 'LY', name: 'Libya' },
  [Country.MA]: { code: 'MA', name: 'Morocco' },
  [Country.MC]: { code: 'MC', name: 'Monaco' },
  [Country.MD]: { code: 'MD', name: 'Moldova' },
  [Country.ME]: { code: 'ME', name: 'Montenegro' },
  [Country.MF]: { code: 'MF', name: 'Saint Martin (French part)' },
  [Country.MG]: { code: 'MG', name: 'Madagascar' },
  [Country.MH]: { code: 'MH', name: 'Marshall Islands' },
  [Country.MK]: { code: 'MK', name: 'North Macedonia' },
  [Country.ML]: { code: 'ML', name: 'Mali' },
  [Country.MM]: { code: 'MM', name: 'Myanmar' },
  [Country.MN]: { code: 'MN', name: 'Mongolia' },
  [Country.MO]: { code: 'MO', name: 'Macao' },
  [Country.MP]: { code: 'MP', name: 'Northern Mariana Islands' },
  [Country.MQ]: { code: 'MQ', name: 'Martinique' },
  [Country.MR]: { code: 'MR', name: 'Mauritania' },
  [Country.MS]: { code: 'MS', name: 'Montserrat' },
  [Country.MT]: { code: 'MT', name: 'Malta' },
  [Country.MU]: { code: 'MU', name: 'Mauritius' },
  [Country.MV]: { code: 'MV', name: 'Maldives' },
  [Country.MW]: { code: 'MW', name: 'Malawi' },
  [Country.MX]: { code: 'MX', name: 'Mexico' },
  [Country.MY]: { code: 'MY', name: 'Malaysia' },
  [Country.MZ]: { code: 'MZ', name: 'Mozambique' },
  [Country.NA]: { code: 'NA', name: 'Namibia' },
  [Country.NC]: { code: 'NC', name: 'New Caledonia' },
  [Country.NE]: { code: 'NE', name: 'Niger' },
  [Country.NF]: { code: 'NF', name: 'Norfolk Island' },
  [Country.NG]: { code: 'NG', name: 'Nigeria' },
  [Country.NI]: { code: 'NI', name: 'Nicaragua' },
  [Country.NL]: { code: 'NL', name: 'Netherlands' },
  [Country.NO]: { code: 'NO', name: 'Norway' },
  [Country.NP]: { code: 'NP', name: 'Nepal' },
  [Country.NR]: { code: 'NR', name: 'Nauru' },
  [Country.NU]: { code: 'NU', name: 'Niue' },
  [Country.NZ]: { code: 'NZ', name: 'New Zealand' },
  [Country.OM]: { code: 'OM', name: 'Oman' },
  [Country.PA]: { code: 'PA', name: 'Panama' },
  [Country.PE]: { code: 'PE', name: 'Peru' },
  [Country.PF]: { code: 'PF', name: 'French Polynesia' },
  [Country.PG]: { code: 'PG', name: 'Papua New Guinea' },
  [Country.PH]: { code: 'PH', name: 'Philippines' },
  [Country.PK]: { code: 'PK', name: 'Pakistan' },
  [Country.PL]: { code: 'PL', name: 'Poland' },
  [Country.PM]: { code: 'PM', name: 'Saint Pierre and Miquelon' },
  [Country.PN]: { code: 'PN', name: 'Pitcairn' },
  [Country.PR]: { code: 'PR', name: 'Puerto Rico' },
  [Country.PS]: { code: 'PS', name: 'Palestine' },
  [Country.PT]: { code: 'PT', name: 'Portugal' },
  [Country.PW]: { code: 'PW', name: 'Palau' },
  [Country.PY]: { code: 'PY', name: 'Paraguay' },
  [Country.QA]: { code: 'QA', name: 'Qatar' },
  [Country.RE]: { code: 'RE', name: 'Réunion' },
  [Country.RO]: { code: 'RO', name: 'Romania' },
  [Country.RS]: { code: 'RS', name: 'Serbia' },
  [Country.RU]: { code: 'RU', name: 'Russian Federation' },
  [Country.RW]: { code: 'RW', name: 'Rwanda' },
  [Country.SA]: { code: 'SA', name: 'Saudi Arabia' },
  [Country.SB]: { code: 'SB', name: 'Solomon Islands' },
  [Country.SC]: { code: 'SC', name: 'Seychelles' },
  [Country.SD]: { code: 'SD', name: 'Sudan' },
  [Country.SE]: { code: 'SE', name: 'Sweden' },
  [Country.SG]: { code: 'SG', name: 'Singapore' },
  [Country.SH]: { code: 'SH', name: 'Saint Helena' },
  [Country.SI]: { code: 'SI', name: 'Slovenia' },
  [Country.SJ]: { code: 'SJ', name: 'Svalbard and Jan Mayen' },
  [Country.SK]: { code: 'SK', name: 'Slovakia' },
  [Country.SL]: { code: 'SL', name: 'Sierra Leone' },
  [Country.SM]: { code: 'SM', name: 'San Marino' },
  [Country.SN]: { code: 'SN', name: 'Senegal' },
  [Country.SO]: { code: 'SO', name: 'Somalia' },
  [Country.SR]: { code: 'SR', name: 'Suriname' },
  [Country.SS]: { code: 'SS', name: 'South Sudan' },
  [Country.ST]: { code: 'ST', name: 'Sao Tome and Principe' },
  [Country.SV]: { code: 'SV', name: 'El Salvador' },
  [Country.SX]: { code: 'SX', name: 'Sint Maarten (Dutch part)' },
  [Country.SY]: { code: 'SY', name: 'Syrian Arab Republic' },
  [Country.SZ]: { code: 'SZ', name: 'Eswatini' },
  [Country.TC]: { code: 'TC', name: 'Turks and Caicos Islands' },
  [Country.TD]: { code: 'TD', name: 'Chad' },
  [Country.TF]: { code: 'TF', name: 'French Southern Territories' },
  [Country.TG]: { code: 'TG', name: 'Togo' },
  [Country.TH]: { code: 'TH', name: 'Thailand' },
  [Country.TJ]: { code: 'TJ', name: 'Tajikistan' },
  [Country.TK]: { code: 'TK', name: 'Tokelau' },
  [Country.TL]: { code: 'TL', name: 'Timor-Leste' },
  [Country.TM]: { code: 'TM', name: 'Turkmenistan' },
  [Country.TN]: { code: 'TN', name: 'Tunisia' },
  [Country.TO]: { code: 'TO', name: 'Tonga' },
  [Country.TR]: { code: 'TR', name: 'Turkey' },
  [Country.TT]: { code: 'TT', name: 'Trinidad and Tobago' },
  [Country.TV]: { code: 'TV', name: 'Tuvalu' },
  [Country.TW]: { code: 'TW', name: 'Taiwan' },
  [Country.TZ]: { code: 'TZ', name: 'Tanzania' },
  [Country.UA]: { code: 'UA', name: 'Ukraine' },
  [Country.UG]: { code: 'UG', name: 'Uganda' },
  [Country.UM]: { code: 'UM', name: 'United States Minor Outlying Islands' },
  [Country.US]: { code: 'US', name: 'United States of America' },
  [Country.UY]: { code: 'UY', name: 'Uruguay' },
  [Country.UZ]: { code: 'UZ', name: 'Uzbekistan' },
  [Country.VA]: { code: 'VA', name: 'Holy See' },
  [Country.VC]: { code: 'VC', name: 'Saint Vincent and the Grenadines' },
  [Country.VE]: { code: 'VE', name: 'Venezuela (Bolivarian Republic of)' },
  [Country.VG]: { code: 'VG', name: 'Virgin Islands (British)' },
  [Country.VI]: { code: 'VI', name: 'Virgin Islands (U.S.)' },
  [Country.VN]: { code: 'VN', name: 'Viet Nam' },
  [Country.VU]: { code: 'VU', name: 'Vanuatu' },
  [Country.WF]: { code: 'WF', name: 'Wallis and Futuna' },
  [Country.WS]: { code: 'WS', name: 'Samoa' },
  [Country.YE]: { code: 'YE', name: 'Yemen' },
  [Country.YT]: { code: 'YT', name: 'Mayotte' },
  [Country.ZA]: { code: 'ZA', name: 'South Africa' },
  [Country.ZM]: { code: 'ZM', name: 'Zambia' },
  [Country.ZW]: { code: 'ZW', name: 'Zimbabwe' }
};

const COUNTRY_CODES = Object.values(Country);

const COMMON_ALIASES = [
  { commonIdentifier: 'UK', trueIdentifier: 'GB' },
  { commonIdentifier: 'USA', trueIdentifier: 'US' }
];

function findCountry(countryIdentifier: string): CountryDetails | undefined {
  return findCountryByCode(countryIdentifier) || findCountryByName(countryIdentifier);
}

function findCountryByName(countryName: string): CountryDetails | undefined {
  return Object.values(CountryProps).find(c => c.name.toUpperCase() === countryName.toUpperCase());
}

function findCountryByCode(countryCode: string): CountryDetails | undefined {
  return Object.values(CountryProps).find(c => c.code === replaceCommonAliases(countryCode.toUpperCase()));
}

function replaceCommonAliases(countryCode: string) {
  if (!countryCode) return null;
  return COMMON_ALIASES.find(ca => ca.commonIdentifier === countryCode)?.trueIdentifier || countryCode;
}

export { COUNTRY_CODES, CountryProps, Country, findCountry, findCountryByCode, findCountryByName };
