import { mapValues } from 'lodash';
import { GroupRoleEnum as GroupRole } from '../prisma/enum-adapter';

const GROUP_ROLES = Object.values(GroupRole);

const PRIVELEGED_GROUP_ROLES: GroupRole[] = [
  GroupRole.ADMINISTRATOR,
  GroupRole.DEPUTY_OWNER,
  GroupRole.LEADER,
  GroupRole.MODERATOR,
  GroupRole.OWNER
];

interface GroupRoleProperties {
  name: string;
  isPriveleged: boolean;
}

const GroupRoleProps: { [role in GroupRole]: GroupRoleProperties } = mapValues(
  {
    [GroupRole.ACHIEVER]: { name: 'Achiever' },
    [GroupRole.ADAMANT]: { name: 'Adamant' },
    [GroupRole.ADEPT]: { name: 'Adept' },
    [GroupRole.ADMINISTRATOR]: { name: 'Administrator' },
    [GroupRole.ADMIRAL]: { name: 'Admiral' },
    [GroupRole.ADVENTURER]: { name: 'Adventurer' },
    [GroupRole.AIR]: { name: 'Air' },
    [GroupRole.ANCHOR]: { name: 'Anchor' },
    [GroupRole.APOTHECARY]: { name: 'Apothecary' },
    [GroupRole.ARCHER]: { name: 'Archer' },
    [GroupRole.ARMADYLEAN]: { name: 'Armadylean' },
    [GroupRole.ARTILLERY]: { name: 'Artillery' },
    [GroupRole.ARTISAN]: { name: 'Artisan' },
    [GroupRole.ASGARNIAN]: { name: 'Asgarnian' },
    [GroupRole.ASSASSIN]: { name: 'Assassin' },
    [GroupRole.ASSISTANT]: { name: 'Assistant' },
    [GroupRole.ASTRAL]: { name: 'Astral' },
    [GroupRole.ATHLETE]: { name: 'Athlete' },
    [GroupRole.ATTACKER]: { name: 'Attacker' },
    [GroupRole.BANDIT]: { name: 'Bandit' },
    [GroupRole.BANDOSIAN]: { name: 'Bandosian' },
    [GroupRole.BARBARIAN]: { name: 'Barbarian' },
    [GroupRole.BATTLEMAGE]: { name: 'Battlemage' },
    [GroupRole.BEAST]: { name: 'Beast' },
    [GroupRole.BERSERKER]: { name: 'Berserker' },
    [GroupRole.BLISTERWOOD]: { name: 'Blisterwood' },
    [GroupRole.BLOOD]: { name: 'Blood' },
    [GroupRole.BLUE]: { name: 'Blue' },
    [GroupRole.BOB]: { name: 'Bob' },
    [GroupRole.BODY]: { name: 'Body' },
    [GroupRole.BRASSICAN]: { name: 'Brassican' },
    [GroupRole.BRAWLER]: { name: 'Brawler' },
    [GroupRole.BRIGADIER]: { name: 'Brigadier' },
    [GroupRole.BRIGAND]: { name: 'Brigand' },
    [GroupRole.BRONZE]: { name: 'Bronze' },
    [GroupRole.BRUISER]: { name: 'Bruiser' },
    [GroupRole.BULWARK]: { name: 'Bulwark' },
    [GroupRole.BURGLAR]: { name: 'Burglar' },
    [GroupRole.BURNT]: { name: 'Burnt' },
    [GroupRole.CADET]: { name: 'Cadet' },
    [GroupRole.CAPTAIN]: { name: 'Captain' },
    [GroupRole.CARRY]: { name: 'Carry' },
    [GroupRole.CHAMPION]: { name: 'Champion' },
    [GroupRole.CHAOS]: { name: 'Chaos' },
    [GroupRole.CLERIC]: { name: 'Cleric' },
    [GroupRole.COLLECTOR]: { name: 'Collector' },
    [GroupRole.COLONEL]: { name: 'Colonel' },
    [GroupRole.COMMANDER]: { name: 'Commander' },
    [GroupRole.COMPETITOR]: { name: 'Competitor' },
    [GroupRole.COMPLETIONIST]: { name: 'Completionist' },
    [GroupRole.CONSTRUCTOR]: { name: 'Constructor' },
    [GroupRole.COOK]: { name: 'Cook' },
    [GroupRole.COORDINATOR]: { name: 'Coordinator' },
    [GroupRole.CORPORAL]: { name: 'Corporal' },
    [GroupRole.COSMIC]: { name: 'Cosmic' },
    [GroupRole.COUNCILLOR]: { name: 'Councillor' },
    [GroupRole.CRAFTER]: { name: 'Crafter' },
    [GroupRole.CREW]: { name: 'Crew' },
    [GroupRole.CRUSADER]: { name: 'Crusader' },
    [GroupRole.CUTPURSE]: { name: 'Cutpurse' },
    [GroupRole.DEATH]: { name: 'Death' },
    [GroupRole.DEFENDER]: { name: 'Defender' },
    [GroupRole.DEFILER]: { name: 'Defiler' },
    [GroupRole.DEPUTY_OWNER]: { name: 'Deputy Owner' },
    [GroupRole.DESTROYER]: { name: 'Destroyer' },
    [GroupRole.DIAMOND]: { name: 'Diamond' },
    [GroupRole.DISEASED]: { name: 'Diseased' },
    [GroupRole.DOCTOR]: { name: 'Doctor' },
    [GroupRole.DOGSBODY]: { name: 'Dogsbody' },
    [GroupRole.DRAGON]: { name: 'Dragon' },
    [GroupRole.DRAGONSTONE]: { name: 'Dragonstone' },
    [GroupRole.DRUID]: { name: 'Druid' },
    [GroupRole.DUELLIST]: { name: 'Duellist' },
    [GroupRole.EARTH]: { name: 'Earth' },
    [GroupRole.ELITE]: { name: 'Elite' },
    [GroupRole.EMERALD]: { name: 'Emerald' },
    [GroupRole.ENFORCER]: { name: 'Enforcer' },
    [GroupRole.EPIC]: { name: 'Epic' },
    [GroupRole.EXECUTIVE]: { name: 'Executive' },
    [GroupRole.EXPERT]: { name: 'Expert' },
    [GroupRole.EXPLORER]: { name: 'Explorer' },
    [GroupRole.FARMER]: { name: 'Farmer' },
    [GroupRole.FEEDER]: { name: 'Feeder' },
    [GroupRole.FIGHTER]: { name: 'Fighter' },
    [GroupRole.FIRE]: { name: 'Fire' },
    [GroupRole.FIREMAKER]: { name: 'Firemaker' },
    [GroupRole.FIRESTARTER]: { name: 'Firestarter' },
    [GroupRole.FISHER]: { name: 'Fisher' },
    [GroupRole.FLETCHER]: { name: 'Fletcher' },
    [GroupRole.FORAGER]: { name: 'Forager' },
    [GroupRole.FREMENNIK]: { name: 'Fremennik' },
    [GroupRole.GAMER]: { name: 'Gamer' },
    [GroupRole.GATHERER]: { name: 'Gatherer' },
    [GroupRole.GENERAL]: { name: 'General' },
    [GroupRole.GNOME_CHILD]: { name: 'Gnome Child' },
    [GroupRole.GNOME_ELDER]: { name: 'Gnome Elder' },
    [GroupRole.GOBLIN]: { name: 'Goblin' },
    [GroupRole.GOLD]: { name: 'Gold' },
    [GroupRole.GOON]: { name: 'Goon' },
    [GroupRole.GREEN]: { name: 'Green' },
    [GroupRole.GREY]: { name: 'Grey' },
    [GroupRole.GUARDIAN]: { name: 'Guardian' },
    [GroupRole.GUTHIXIAN]: { name: 'Guthixian' },
    [GroupRole.HARPOON]: { name: 'Harpoon' },
    [GroupRole.HEALER]: { name: 'Healer' },
    [GroupRole.HELLCAT]: { name: 'Hellcat' },
    [GroupRole.HELPER]: { name: 'Helper' },
    [GroupRole.HERBOLOGIST]: { name: 'Herbologist' },
    [GroupRole.HERO]: { name: 'Hero' },
    [GroupRole.HOLY]: { name: 'Holy' },
    [GroupRole.HOARDER]: { name: 'Hoarder' },
    [GroupRole.HUNTER]: { name: 'Hunter' },
    [GroupRole.IGNITOR]: { name: 'Ignitor' },
    [GroupRole.ILLUSIONIST]: { name: 'Illusionist' },
    [GroupRole.IMP]: { name: 'Imp' },
    [GroupRole.INFANTRY]: { name: 'Infantry' },
    [GroupRole.INQUISITOR]: { name: 'Inquisitor' },
    [GroupRole.IRON]: { name: 'Iron' },
    [GroupRole.JADE]: { name: 'Jade' },
    [GroupRole.JUSTICIAR]: { name: 'Justiciar' },
    [GroupRole.KANDARIN]: { name: 'Kandarin' },
    [GroupRole.KARAMJAN]: { name: 'Karamjan' },
    [GroupRole.KHARIDIAN]: { name: 'Kharidian' },
    [GroupRole.KITTEN]: { name: 'Kitten' },
    [GroupRole.KNIGHT]: { name: 'Knight' },
    [GroupRole.LABOURER]: { name: 'Labourer' },
    [GroupRole.LAW]: { name: 'Law' },
    [GroupRole.LEADER]: { name: 'Leader' },
    [GroupRole.LEARNER]: { name: 'Learner' },
    [GroupRole.LEGACY]: { name: 'Legacy' },
    [GroupRole.LEGEND]: { name: 'Legend' },
    [GroupRole.LEGIONNAIRE]: { name: 'Legionnaire' },
    [GroupRole.LIEUTENANT]: { name: 'Lieutenant' },
    [GroupRole.LOOTER]: { name: 'Looter' },
    [GroupRole.LUMBERJACK]: { name: 'Lumberjack' },
    [GroupRole.MAGIC]: { name: 'Magic' },
    [GroupRole.MAGICIAN]: { name: 'Magician' },
    [GroupRole.MAJOR]: { name: 'Major' },
    [GroupRole.MAPLE]: { name: 'Maple' },
    [GroupRole.MARSHAL]: { name: 'Marshal' },
    [GroupRole.MASTER]: { name: 'Master' },
    [GroupRole.MAXED]: { name: 'Maxed' },
    [GroupRole.MEDIATOR]: { name: 'Mediator' },
    [GroupRole.MEDIC]: { name: 'Medic' },
    [GroupRole.MENTOR]: { name: 'Mentor' },
    [GroupRole.MEMBER]: { name: 'Member' },
    [GroupRole.MERCHANT]: { name: 'Merchant' },
    [GroupRole.MIND]: { name: 'Mind' },
    [GroupRole.MINER]: { name: 'Miner' },
    [GroupRole.MINION]: { name: 'Minion' },
    [GroupRole.MISTHALINIAN]: { name: 'Misthalinian' },
    [GroupRole.MITHRIL]: { name: 'Mithril' },
    [GroupRole.MODERATOR]: { name: 'Moderator' },
    [GroupRole.MONARCH]: { name: 'Monarch' },
    [GroupRole.MORYTANIAN]: { name: 'Morytanian' },
    [GroupRole.MYSTIC]: { name: 'Mystic' },
    [GroupRole.MYTH]: { name: 'Myth' },
    [GroupRole.NATURAL]: { name: 'Natural' },
    [GroupRole.NATURE]: { name: 'Nature' },
    [GroupRole.NECROMANCER]: { name: 'Necromancer' },
    [GroupRole.NINJA]: { name: 'Ninja' },
    [GroupRole.NOBLE]: { name: 'Noble' },
    [GroupRole.NOVICE]: { name: 'Novice' },
    [GroupRole.NURSE]: { name: 'Nurse' },
    [GroupRole.OAK]: { name: 'Oak' },
    [GroupRole.OFFICER]: { name: 'Officer' },
    [GroupRole.ONYX]: { name: 'Onyx' },
    [GroupRole.OPAL]: { name: 'Opal' },
    [GroupRole.ORACLE]: { name: 'Oracle' },
    [GroupRole.ORANGE]: { name: 'Orange' },
    [GroupRole.OWNER]: { name: 'Owner' },
    [GroupRole.PAGE]: { name: 'Page' },
    [GroupRole.PALADIN]: { name: 'Paladin' },
    [GroupRole.PAWN]: { name: 'Pawn' },
    [GroupRole.PILGRIM]: { name: 'Pilgrim' },
    [GroupRole.PINE]: { name: 'Pine' },
    [GroupRole.PINK]: { name: 'Pink' },
    [GroupRole.PREFECT]: { name: 'Prefect' },
    [GroupRole.PRIEST]: { name: 'Priest' },
    [GroupRole.PRIVATE]: { name: 'Private' },
    [GroupRole.PRODIGY]: { name: 'Prodigy' },
    [GroupRole.PROSELYTE]: { name: 'Proselyte' },
    [GroupRole.PROSPECTOR]: { name: 'Prospector' },
    [GroupRole.PROTECTOR]: { name: 'Protector' },
    [GroupRole.PURE]: { name: 'Pure' },
    [GroupRole.PURPLE]: { name: 'Purple' },
    [GroupRole.PYROMANCER]: { name: 'Pyromancer' },
    [GroupRole.QUESTER]: { name: 'Quester' },
    [GroupRole.RACER]: { name: 'Racer' },
    [GroupRole.RAIDER]: { name: 'Raider' },
    [GroupRole.RANGER]: { name: 'Ranger' },
    [GroupRole.RECORD_CHASER]: { name: 'Record-Chaser' },
    [GroupRole.RECRUIT]: { name: 'Recruit' },
    [GroupRole.RECRUITER]: { name: 'Recruiter' },
    [GroupRole.RED_TOPAZ]: { name: 'Red Topaz' },
    [GroupRole.RED]: { name: 'Red' },
    [GroupRole.ROGUE]: { name: 'Rogue' },
    [GroupRole.RUBY]: { name: 'Ruby' },
    [GroupRole.RUNE]: { name: 'Rune' },
    [GroupRole.RUNECRAFTER]: { name: 'Runecrafter' },
    [GroupRole.SAGE]: { name: 'Sage' },
    [GroupRole.SAPPHIRE]: { name: 'Sapphire' },
    [GroupRole.SARADOMINIST]: { name: 'Saradominist' },
    [GroupRole.SAVIOUR]: { name: 'Saviour' },
    [GroupRole.SCAVENGER]: { name: 'Scavenger' },
    [GroupRole.SCHOLAR]: { name: 'Scholar' },
    [GroupRole.SCOURGE]: { name: 'Scourge' },
    [GroupRole.SCOUT]: { name: 'Scout' },
    [GroupRole.SCRIBE]: { name: 'Scribe' },
    [GroupRole.SEER]: { name: 'Seer' },
    [GroupRole.SENATOR]: { name: 'Senator' },
    [GroupRole.SENTRY]: { name: 'Sentry' },
    [GroupRole.SERENIST]: { name: 'Serenist' },
    [GroupRole.SERGEANT]: { name: 'Sergeant' },
    [GroupRole.SHAMAN]: { name: 'Shaman' },
    [GroupRole.SHERIFF]: { name: 'Sheriff' },
    [GroupRole.SHORT_GREEN_GUY]: { name: 'Short Green Guy' },
    [GroupRole.SKILLER]: { name: 'Skiller' },
    [GroupRole.SKULLED]: { name: 'Skulled' },
    [GroupRole.SLAYER]: { name: 'Slayer' },
    [GroupRole.SMITER]: { name: 'Smiter' },
    [GroupRole.SMITH]: { name: 'Smith' },
    [GroupRole.SMUGGLER]: { name: 'Smuggler' },
    [GroupRole.SNIPER]: { name: 'Sniper' },
    [GroupRole.SOUL]: { name: 'Soul' },
    [GroupRole.SPECIALIST]: { name: 'Specialist' },
    [GroupRole.SPEED_RUNNER]: { name: 'Speed-Runner' },
    [GroupRole.SPELLCASTER]: { name: 'Spellcaster' },
    [GroupRole.SQUIRE]: { name: 'Squire' },
    [GroupRole.STAFF]: { name: 'Staff' },
    [GroupRole.STEEL]: { name: 'Steel' },
    [GroupRole.STRIDER]: { name: 'Strider' },
    [GroupRole.STRIKER]: { name: 'Striker' },
    [GroupRole.SUMMONER]: { name: 'Summoner' },
    [GroupRole.SUPERIOR]: { name: 'Superior' },
    [GroupRole.SUPERVISOR]: { name: 'Supervisor' },
    [GroupRole.TEACHER]: { name: 'Teacher' },
    [GroupRole.TEMPLAR]: { name: 'Templar' },
    [GroupRole.THERAPIST]: { name: 'Therapist' },
    [GroupRole.THIEF]: { name: 'Thief' },
    [GroupRole.TIRANNIAN]: { name: 'Tirannian' },
    [GroupRole.TRIALIST]: { name: 'Trialist' },
    [GroupRole.TRICKSTER]: { name: 'Trickster' },
    [GroupRole.TZKAL]: { name: 'TzKal' },
    [GroupRole.TZTOK]: { name: 'TzTok' },
    [GroupRole.UNHOLY]: { name: 'Unholy' },
    [GroupRole.VAGRANT]: { name: 'Vagrant' },
    [GroupRole.VANGUARD]: { name: 'Vanguard' },
    [GroupRole.WALKER]: { name: 'Walker' },
    [GroupRole.WANDERER]: { name: 'Wanderer' },
    [GroupRole.WARDEN]: { name: 'Warden' },
    [GroupRole.WARLOCK]: { name: 'Warlock' },
    [GroupRole.WARRIOR]: { name: 'Warrior' },
    [GroupRole.WATER]: { name: 'Water' },
    [GroupRole.WILD]: { name: 'Wild' },
    [GroupRole.WILLOW]: { name: 'Willow' },
    [GroupRole.WILY]: { name: 'Wily' },
    [GroupRole.WINTUMBER]: { name: 'Wintumber' },
    [GroupRole.WITCH]: { name: 'Witch' },
    [GroupRole.WIZARD]: { name: 'Wizard' },
    [GroupRole.WORKER]: { name: 'Worker' },
    [GroupRole.WRATH]: { name: 'Wrath' },
    [GroupRole.XERICIAN]: { name: 'Xerician' },
    [GroupRole.YELLOW]: { name: 'Yellow' },
    [GroupRole.YEW]: { name: 'Yew' },
    [GroupRole.ZAMORAKIAN]: { name: 'Zamorakian' },
    [GroupRole.ZAROSIAN]: { name: 'Zarosian' },
    [GroupRole.ZEALOT]: { name: 'Zealot' },
    [GroupRole.ZENYTE]: { name: 'Zenyte' }
  },
  (props, key: GroupRole) => ({
    ...props,
    isPriveleged: PRIVELEGED_GROUP_ROLES.includes(key as GroupRole)
  })
);

function findGroupRole(roleName: string): GroupRole | null {
  for (const [key, value] of Object.entries(GroupRoleProps)) {
    if (value.name.toUpperCase() === roleName.toUpperCase()) {
      return key as GroupRole;
    }
  }

  return null;
}

export { GroupRole, GroupRoleProps, GROUP_ROLES, PRIVELEGED_GROUP_ROLES, findGroupRole };
