version: '3'
services:
  redis:
    container_name: redis
    image: redis
    env_file:
      - ./.env
    expose:
      - '6379'
    ports:
      - '6379:6379'
  db:
    container_name: db
    image: postgres:14
    env_file:
      - ./.env
    expose:
      - '5432'
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    env_file:
      - ./.env
    ports:
      - '54321:80'
    depends_on:
      - db
    logging:
      driver: none
volumes:
  pgdata:
