FROM node:16.14 as builder

WORKDIR /wise-old-man/server

COPY package*.json ./
COPY prisma ./prisma/

RUN npm install -s
COPY . .
RUN npm run build


FROM node:16.14-slim
WORKDIR /wise-old-man/server
COPY --from=builder /wise-old-man/server ./

# Prisma Migrate requires openssl to be installed (slim build doesn't have it)
RUN apt-get update
RUN apt-get install -y openssl

# Wait for the database container to be open on port 5432, then start the API
CMD ./wait-for-it.sh -t 30 db:5432 -- npm run dev