FROM node:16.14 as builder

WORKDIR /wise-old-man/server

COPY package*.json ./
COPY prisma ./prisma/

RUN npm install -s
COPY . .
RUN npm run build


FROM node:16.14-slim
WORKDIR /wise-old-man/server
COPY --from=builder /wise-old-man/server ./

RUN npm install pm2 -g -s

CMD ["npm", "start"]