enum GroupRole {
  ACHIEVER = 'achiever',
  ADAMANT = 'adamant',
  ADEPT = 'adept',
  ADMINISTRATOR = 'administrator',
  ADMIRAL = 'admiral',
  ADVENTURER = 'adventurer',
  AIR = 'air',
  ANCHOR = 'anchor',
  APOTHECARY = 'apothecary',
  ARCHER = 'archer',
  ARMADYLEAN = 'armadylean',
  ARTILLERY = 'artillery',
  ARTISAN = 'artisan',
  ASGARNIAN = 'asgarnian',
  ASSASSIN = 'assassin',
  ASSISTANT = 'assistant',
  ASTRAL = 'astral',
  ATHLETE = 'athlete',
  ATTACKER = 'attacker',
  BANDIT = 'bandit',
  BANDOSIAN = 'bandosian',
  BARBARIAN = 'barbarian',
  BATTLEMAGE = 'battlemage',
  BEAST = 'beast',
  BERSERKER = 'berserker',
  BLISTERWOOD = 'blisterwood',
  BLOOD = 'blood',
  BLUE = 'blue',
  BOB = 'bob',
  BODY = 'body',
  BRASSICAN = 'brassican',
  BRAWLER = 'brawler',
  BRIGADIER = 'brigadier',
  BRIGAND = 'brigand',
  BRONZE = 'bronze',
  BRUISER = 'bruiser',
  BULWARK = 'bulwark',
  BURGLAR = 'burglar',
  BURNT = 'burnt',
  CADET = 'cadet',
  CAPTAIN = 'captain',
  CARRY = 'carry',
  CHAMPION = 'champion',
  CHAOS = 'chaos',
  CLERIC = 'cleric',
  COLLECTOR = 'collector',
  COLONEL = 'colonel',
  COMMANDER = 'commander',
  COMPETITOR = 'competitor',
  COMPLETIONIST = 'completionist',
  CONSTRUCTOR = 'constructor',
  COOK = 'cook',
  COORDINATOR = 'coordinator',
  CORPORAL = 'corporal',
  COSMIC = 'cosmic',
  COUNCILLOR = 'councillor',
  CRAFTER = 'crafter',
  CREW = 'crew',
  CRUSADER = 'crusader',
  CUTPURSE = 'cutpurse',
  DEATH = 'death',
  DEFENDER = 'defender',
  DEFILER = 'defiler',
  DEPUTY_OWNER = 'deputy_owner',
  DESTROYER = 'destroyer',
  DIAMOND = 'diamond',
  DISEASED = 'diseased',
  DOCTOR = 'doctor',
  DOGSBODY = 'dogsbody',
  DRAGON = 'dragon',
  DRAGONSTONE = 'dragonstone',
  DRUID = 'druid',
  DUELLIST = 'duellist',
  EARTH = 'earth',
  ELITE = 'elite',
  EMERALD = 'emerald',
  ENFORCER = 'enforcer',
  EPIC = 'epic',
  EXECUTIVE = 'executive',
  EXPERT = 'expert',
  EXPLORER = 'explorer',
  FARMER = 'farmer',
  FEEDER = 'feeder',
  FIGHTER = 'fighter',
  FIRE = 'fire',
  FIREMAKER = 'firemaker',
  FIRESTARTER = 'firestarter',
  FISHER = 'fisher',
  FLETCHER = 'fletcher',
  FORAGER = 'forager',
  FREMENNIK = 'fremennik',
  GAMER = 'gamer',
  GATHERER = 'gatherer',
  GENERAL = 'general',
  GNOME_CHILD = 'gnome_child',
  GNOME_ELDER = 'gnome_elder',
  GOBLIN = 'goblin',
  GOLD = 'gold',
  GOON = 'goon',
  GREEN = 'green',
  GREY = 'grey',
  GUARDIAN = 'guardian',
  GUTHIXIAN = 'guthixian',
  HARPOON = 'harpoon',
  HEALER = 'healer',
  HELLCAT = 'hellcat',
  HELPER = 'helper',
  HERBOLOGIST = 'herbologist',
  HERO = 'hero',
  HOLY = 'holy',
  HOARDER = 'hoarder',
  HUNTER = 'hunter',
  IGNITOR = 'ignitor',
  ILLUSIONIST = 'illusionist',
  IMP = 'imp',
  INFANTRY = 'infantry',
  INQUISITOR = 'inquisitor',
  IRON = 'iron',
  JADE = 'jade',
  JUSTICIAR = 'justiciar',
  KANDARIN = 'kandarin',
  KARAMJAN = 'karamjan',
  KHARIDIAN = 'kharidian',
  KITTEN = 'kitten',
  KNIGHT = 'knight',
  LABOURER = 'labourer',
  LAW = 'law',
  LEADER = 'leader',
  LEARNER = 'learner',
  LEGACY = 'legacy',
  LEGEND = 'legend',
  LEGIONNAIRE = 'legionnaire',
  LIEUTENANT = 'lieutenant',
  LOOTER = 'looter',
  LUMBERJACK = 'lumberjack',
  MAGIC = 'magic',
  MAGICIAN = 'magician',
  MAJOR = 'major',
  MAPLE = 'maple',
  MARSHAL = 'marshal',
  MASTER = 'master',
  MAXED = 'maxed',
  MEDIATOR = 'mediator',
  MEDIC = 'medic',
  MENTOR = 'mentor',
  MEMBER = 'member',
  MERCHANT = 'merchant',
  MIND = 'mind',
  MINER = 'miner',
  MINION = 'minion',
  MISTHALINIAN = 'misthalinian',
  MITHRIL = 'mithril',
  MODERATOR = 'moderator',
  MONARCH = 'monarch',
  MORYTANIAN = 'morytanian',
  MYSTIC = 'mystic',
  MYTH = 'myth',
  NATURAL = 'natural',
  NATURE = 'nature',
  NECROMANCER = 'necromancer',
  NINJA = 'ninja',
  NOBLE = 'noble',
  NOVICE = 'novice',
  NURSE = 'nurse',
  OAK = 'oak',
  OFFICER = 'officer',
  ONYX = 'onyx',
  OPAL = 'opal',
  ORACLE = 'oracle',
  ORANGE = 'orange',
  OWNER = 'owner',
  PAGE = 'page',
  PALADIN = 'paladin',
  PAWN = 'pawn',
  PILGRIM = 'pilgrim',
  PINE = 'pine',
  PINK = 'pink',
  PREFECT = 'prefect',
  PRIEST = 'priest',
  PRIVATE = 'private',
  PRODIGY = 'prodigy',
  PROSELYTE = 'proselyte',
  PROSPECTOR = 'prospector',
  PROTECTOR = 'protector',
  PURE = 'pure',
  PURPLE = 'purple',
  PYROMANCER = 'pyromancer',
  QUESTER = 'quester',
  RACER = 'racer',
  RAIDER = 'raider',
  RANGER = 'ranger',
  RECORD_CHASER = 'record_chaser',
  RECRUIT = 'recruit',
  RECRUITER = 'recruiter',
  RED_TOPAZ = 'red_topaz',
  RED = 'red',
  ROGUE = 'rogue',
  RUBY = 'ruby',
  RUNE = 'rune',
  RUNECRAFTER = 'runecrafter',
  SAGE = 'sage',
  SAPPHIRE = 'sapphire',
  SARADOMINIST = 'saradominist',
  SAVIOUR = 'saviour',
  SCAVENGER = 'scavenger',
  SCHOLAR = 'scholar',
  SCOURGE = 'scourge',
  SCOUT = 'scout',
  SCRIBE = 'scribe',
  SEER = 'seer',
  SENATOR = 'senator',
  SENTRY = 'sentry',
  SERENIST = 'serenist',
  SERGEANT = 'sergeant',
  SHAMAN = 'shaman',
  SHERIFF = 'sheriff',
  SHORT_GREEN_GUY = 'short_green_guy',
  SKILLER = 'skiller',
  SKULLED = 'skulled',
  SLAYER = 'slayer',
  SMITER = 'smiter',
  SMITH = 'smith',
  SMUGGLER = 'smuggler',
  SNIPER = 'sniper',
  SOUL = 'soul',
  SPECIALIST = 'specialist',
  SPEED_RUNNER = 'speed_runner',
  SPELLCASTER = 'spellcaster',
  SQUIRE = 'squire',
  STAFF = 'staff',
  STEEL = 'steel',
  STRIDER = 'strider',
  STRIKER = 'striker',
  SUMMONER = 'summoner',
  SUPERIOR = 'superior',
  SUPERVISOR = 'supervisor',
  TEACHER = 'teacher',
  TEMPLAR = 'templar',
  THERAPIST = 'therapist',
  THIEF = 'thief',
  TIRANNIAN = 'tirannian',
  TRIALIST = 'trialist',
  TRICKSTER = 'trickster',
  TZKAL = 'tzkal',
  TZTOK = 'tztok',
  UNHOLY = 'unholy',
  VAGRANT = 'vagrant',
  VANGUARD = 'vanguard',
  WALKER = 'walker',
  WANDERER = 'wanderer',
  WARDEN = 'warden',
  WARLOCK = 'warlock',
  WARRIOR = 'warrior',
  WATER = 'water',
  WILD = 'wild',
  WILLOW = 'willow',
  WILY = 'wily',
  WINTUMBER = 'wintumber',
  WITCH = 'witch',
  WIZARD = 'wizard',
  WORKER = 'worker',
  WRATH = 'wrath',
  XERICIAN = 'xerician',
  YELLOW = 'yellow',
  YEW = 'yew',
  ZAMORAKIAN = 'zamorakian',
  ZAROSIAN = 'zarosian',
  ZEALOT = 'zealot',
  ZENYTE = 'zenyte'
}

const GroupRoleProps = {
  [GroupRole.ACHIEVER]: { value: 'achiever', name: 'Achiever', isPriveleged: false },
  [GroupRole.ADAMANT]: { value: 'adamant', name: 'Adamant', isPriveleged: false },
  [GroupRole.ADEPT]: { value: 'adept', name: 'Adept', isPriveleged: false },
  [GroupRole.ADMINISTRATOR]: { value: 'administrator', name: 'Administrator', isPriveleged: true },
  [GroupRole.ADMIRAL]: { value: 'admiral', name: 'Admiral', isPriveleged: false },
  [GroupRole.ADVENTURER]: { value: 'adventurer', name: 'Adventurer', isPriveleged: false },
  [GroupRole.AIR]: { value: 'air', name: 'Air', isPriveleged: false },
  [GroupRole.ANCHOR]: { value: 'anchor', name: 'Anchor', isPriveleged: false },
  [GroupRole.APOTHECARY]: { value: 'apothecary', name: 'Apothecary', isPriveleged: false },
  [GroupRole.ARCHER]: { value: 'archer', name: 'Archer', isPriveleged: false },
  [GroupRole.ARMADYLEAN]: { value: 'armadylean', name: 'Armadylean', isPriveleged: false },
  [GroupRole.ARTILLERY]: { value: 'artillery', name: 'Artillery', isPriveleged: false },
  [GroupRole.ARTISAN]: { value: 'artisan', name: 'Artisan', isPriveleged: false },
  [GroupRole.ASGARNIAN]: { value: 'asgarnian', name: 'Asgarnian', isPriveleged: false },
  [GroupRole.ASSASSIN]: { value: 'assassin', name: 'Assassin', isPriveleged: false },
  [GroupRole.ASSISTANT]: { value: 'assistant', name: 'Assistant', isPriveleged: false },
  [GroupRole.ASTRAL]: { value: 'astral', name: 'Astral', isPriveleged: false },
  [GroupRole.ATHLETE]: { value: 'athlete', name: 'Athlete', isPriveleged: false },
  [GroupRole.ATTACKER]: { value: 'attacker', name: 'Attacker', isPriveleged: false },
  [GroupRole.BANDIT]: { value: 'bandit', name: 'Bandit', isPriveleged: false },
  [GroupRole.BANDOSIAN]: { value: 'bandosian', name: 'Bandosian', isPriveleged: false },
  [GroupRole.BARBARIAN]: { value: 'barbarian', name: 'Barbarian', isPriveleged: false },
  [GroupRole.BATTLEMAGE]: { value: 'battlemage', name: 'Battlemage', isPriveleged: false },
  [GroupRole.BEAST]: { value: 'beast', name: 'Beast', isPriveleged: false },
  [GroupRole.BERSERKER]: { value: 'berserker', name: 'Berserker', isPriveleged: false },
  [GroupRole.BLISTERWOOD]: { value: 'blisterwood', name: 'Blisterwood', isPriveleged: false },
  [GroupRole.BLOOD]: { value: 'blood', name: 'Blood', isPriveleged: false },
  [GroupRole.BLUE]: { value: 'blue', name: 'Blue', isPriveleged: false },
  [GroupRole.BOB]: { value: 'bob', name: 'Bob', isPriveleged: false },
  [GroupRole.BODY]: { value: 'body', name: 'Body', isPriveleged: false },
  [GroupRole.BRASSICAN]: { value: 'brassican', name: 'Brassican', isPriveleged: false },
  [GroupRole.BRAWLER]: { value: 'brawler', name: 'Brawler', isPriveleged: false },
  [GroupRole.BRIGADIER]: { value: 'brigadier', name: 'Brigadier', isPriveleged: false },
  [GroupRole.BRIGAND]: { value: 'brigand', name: 'Brigand', isPriveleged: false },
  [GroupRole.BRONZE]: { value: 'bronze', name: 'Bronze', isPriveleged: false },
  [GroupRole.BRUISER]: { value: 'bruiser', name: 'Bruiser', isPriveleged: false },
  [GroupRole.BULWARK]: { value: 'bulwark', name: 'Bulwark', isPriveleged: false },
  [GroupRole.BURGLAR]: { value: 'burglar', name: 'Burglar', isPriveleged: false },
  [GroupRole.BURNT]: { value: 'burnt', name: 'Burnt', isPriveleged: false },
  [GroupRole.CADET]: { value: 'cadet', name: 'Cadet', isPriveleged: false },
  [GroupRole.CAPTAIN]: { value: 'captain', name: 'Captain', isPriveleged: false },
  [GroupRole.CARRY]: { value: 'carry', name: 'Carry', isPriveleged: false },
  [GroupRole.CHAMPION]: { value: 'champion', name: 'Champion', isPriveleged: false },
  [GroupRole.CHAOS]: { value: 'chaos', name: 'Chaos', isPriveleged: false },
  [GroupRole.CLERIC]: { value: 'cleric', name: 'Cleric', isPriveleged: false },
  [GroupRole.COLLECTOR]: { value: 'collector', name: 'Collector', isPriveleged: false },
  [GroupRole.COLONEL]: { value: 'colonel', name: 'Colonel', isPriveleged: false },
  [GroupRole.COMMANDER]: { value: 'commander', name: 'Commander', isPriveleged: false },
  [GroupRole.COMPETITOR]: { value: 'competitor', name: 'Competitor', isPriveleged: false },
  [GroupRole.COMPLETIONIST]: { value: 'completionist', name: 'Completionist', isPriveleged: false },
  [GroupRole.CONSTRUCTOR]: { value: 'constructor', name: 'Constructor', isPriveleged: false },
  [GroupRole.COOK]: { value: 'cook', name: 'Cook', isPriveleged: false },
  [GroupRole.COORDINATOR]: { value: 'coordinator', name: 'Coordinator', isPriveleged: false },
  [GroupRole.CORPORAL]: { value: 'corporal', name: 'Corporal', isPriveleged: false },
  [GroupRole.COSMIC]: { value: 'cosmic', name: 'Cosmic', isPriveleged: false },
  [GroupRole.COUNCILLOR]: { value: 'councillor', name: 'Councillor', isPriveleged: false },
  [GroupRole.CRAFTER]: { value: 'crafter', name: 'Crafter', isPriveleged: false },
  [GroupRole.CREW]: { value: 'crew', name: 'Crew', isPriveleged: false },
  [GroupRole.CRUSADER]: { value: 'crusader', name: 'Crusader', isPriveleged: false },
  [GroupRole.CUTPURSE]: { value: 'cutpurse', name: 'Cutpurse', isPriveleged: false },
  [GroupRole.DEATH]: { value: 'death', name: 'Death', isPriveleged: false },
  [GroupRole.DEFENDER]: { value: 'defender', name: 'Defender', isPriveleged: false },
  [GroupRole.DEFILER]: { value: 'defiler', name: 'Defiler', isPriveleged: false },
  [GroupRole.DEPUTY_OWNER]: { value: 'deputy owner', name: 'Deputy owner', isPriveleged: true },
  [GroupRole.DESTROYER]: { value: 'destroyer', name: 'Destroyer', isPriveleged: false },
  [GroupRole.DIAMOND]: { value: 'diamond', name: 'Diamond', isPriveleged: false },
  [GroupRole.DISEASED]: { value: 'diseased', name: 'Diseased', isPriveleged: false },
  [GroupRole.DOCTOR]: { value: 'doctor', name: 'Doctor', isPriveleged: false },
  [GroupRole.DOGSBODY]: { value: 'dogsbody', name: 'Dogsbody', isPriveleged: false },
  [GroupRole.DRAGON]: { value: 'dragon', name: 'Dragon', isPriveleged: false },
  [GroupRole.DRAGONSTONE]: { value: 'dragonstone', name: 'Dragonstone', isPriveleged: false },
  [GroupRole.DRUID]: { value: 'druid', name: 'Druid', isPriveleged: false },
  [GroupRole.DUELLIST]: { value: 'duellist', name: 'Duellist', isPriveleged: false },
  [GroupRole.EARTH]: { value: 'earth', name: 'Earth', isPriveleged: false },
  [GroupRole.ELITE]: { value: 'elite', name: 'Elite', isPriveleged: false },
  [GroupRole.EMERALD]: { value: 'emerald', name: 'Emerald', isPriveleged: false },
  [GroupRole.ENFORCER]: { value: 'enforcer', name: 'Enforcer', isPriveleged: false },
  [GroupRole.EPIC]: { value: 'epic', name: 'Epic', isPriveleged: false },
  [GroupRole.EXECUTIVE]: { value: 'executive', name: 'Executive', isPriveleged: false },
  [GroupRole.EXPERT]: { value: 'expert', name: 'Expert', isPriveleged: false },
  [GroupRole.EXPLORER]: { value: 'explorer', name: 'Explorer', isPriveleged: false },
  [GroupRole.FARMER]: { value: 'farmer', name: 'Farmer', isPriveleged: false },
  [GroupRole.FEEDER]: { value: 'feeder', name: 'Feeder', isPriveleged: false },
  [GroupRole.FIGHTER]: { value: 'fighter', name: 'Fighter', isPriveleged: false },
  [GroupRole.FIRE]: { value: 'fire', name: 'Fire', isPriveleged: false },
  [GroupRole.FIREMAKER]: { value: 'firemaker', name: 'Firemaker', isPriveleged: false },
  [GroupRole.FIRESTARTER]: { value: 'firestarter', name: 'Firestarter', isPriveleged: false },
  [GroupRole.FISHER]: { value: 'fisher', name: 'Fisher', isPriveleged: false },
  [GroupRole.FLETCHER]: { value: 'fletcher', name: 'Fletcher', isPriveleged: false },
  [GroupRole.FORAGER]: { value: 'forager', name: 'Forager', isPriveleged: false },
  [GroupRole.FREMENNIK]: { value: 'fremennik', name: 'Fremennik', isPriveleged: false },
  [GroupRole.GAMER]: { value: 'gamer', name: 'Gamer', isPriveleged: false },
  [GroupRole.GATHERER]: { value: 'gatherer', name: 'Gatherer', isPriveleged: false },
  [GroupRole.GENERAL]: { value: 'general', name: 'General', isPriveleged: false },
  [GroupRole.GNOME_CHILD]: { value: 'gnome child', name: 'Gnome Child', isPriveleged: false },
  [GroupRole.GNOME_ELDER]: { value: 'gnome elder', name: 'Gnome Elder', isPriveleged: false },
  [GroupRole.GOBLIN]: { value: 'goblin', name: 'Goblin', isPriveleged: false },
  [GroupRole.GOLD]: { value: 'gold', name: 'Gold', isPriveleged: false },
  [GroupRole.GOON]: { value: 'goon', name: 'Goon', isPriveleged: false },
  [GroupRole.GREEN]: { value: 'green', name: 'Green', isPriveleged: false },
  [GroupRole.GREY]: { value: 'grey', name: 'Grey', isPriveleged: false },
  [GroupRole.GUARDIAN]: { value: 'guardian', name: 'Guardian', isPriveleged: false },
  [GroupRole.GUTHIXIAN]: { value: 'guthixian', name: 'Guthixian', isPriveleged: false },
  [GroupRole.HARPOON]: { value: 'harpoon', name: 'Harpoon', isPriveleged: false },
  [GroupRole.HEALER]: { value: 'healer', name: 'Healer', isPriveleged: false },
  [GroupRole.HELLCAT]: { value: 'hellcat', name: 'Hellcat', isPriveleged: false },
  [GroupRole.HELPER]: { value: 'helper', name: 'Helper', isPriveleged: false },
  [GroupRole.HERBOLOGIST]: { value: 'herbologist', name: 'Herbologist', isPriveleged: false },
  [GroupRole.HERO]: { value: 'hero', name: 'Hero', isPriveleged: false },
  [GroupRole.HOLY]: { value: 'holy', name: 'Holy', isPriveleged: false },
  [GroupRole.HOARDER]: { value: 'hoarder', name: 'Hoarder', isPriveleged: false },
  [GroupRole.HUNTER]: { value: 'hunter', name: 'Hunter', isPriveleged: false },
  [GroupRole.IGNITOR]: { value: 'ignitor', name: 'Ignitor', isPriveleged: false },
  [GroupRole.ILLUSIONIST]: { value: 'illusionist', name: 'Illusionist', isPriveleged: false },
  [GroupRole.IMP]: { value: 'imp', name: 'Imp', isPriveleged: false },
  [GroupRole.INFANTRY]: { value: 'infantry', name: 'Infantry', isPriveleged: false },
  [GroupRole.INQUISITOR]: { value: 'inquisitor', name: 'Inquisitor', isPriveleged: false },
  [GroupRole.IRON]: { value: 'iron', name: 'Iron', isPriveleged: false },
  [GroupRole.JADE]: { value: 'jade', name: 'Jade', isPriveleged: false },
  [GroupRole.JUSTICIAR]: { value: 'justiciar', name: 'Justiciar', isPriveleged: false },
  [GroupRole.KANDARIN]: { value: 'kandarin', name: 'Kandarin', isPriveleged: false },
  [GroupRole.KARAMJAN]: { value: 'karamjan', name: 'Karamjan', isPriveleged: false },
  [GroupRole.KHARIDIAN]: { value: 'kharidian', name: 'Kharidian', isPriveleged: false },
  [GroupRole.KITTEN]: { value: 'kitten', name: 'Kitten', isPriveleged: false },
  [GroupRole.KNIGHT]: { value: 'knight', name: 'Knight', isPriveleged: false },
  [GroupRole.LABOURER]: { value: 'labourer', name: 'Labourer', isPriveleged: false },
  [GroupRole.LAW]: { value: 'law', name: 'Law', isPriveleged: false },
  [GroupRole.LEADER]: { value: 'leader', name: 'Leader', isPriveleged: true },
  [GroupRole.LEARNER]: { value: 'learner', name: 'Learner', isPriveleged: false },
  [GroupRole.LEGACY]: { value: 'legacy', name: 'Legacy', isPriveleged: false },
  [GroupRole.LEGEND]: { value: 'legend', name: 'Legend', isPriveleged: false },
  [GroupRole.LEGIONNAIRE]: { value: 'legionnaire', name: 'Legionnaire', isPriveleged: false },
  [GroupRole.LIEUTENANT]: { value: 'lieutenant', name: 'Lieutenant', isPriveleged: false },
  [GroupRole.LOOTER]: { value: 'looter', name: 'Looter', isPriveleged: false },
  [GroupRole.LUMBERJACK]: { value: 'lumberjack', name: 'Lumberjack', isPriveleged: false },
  [GroupRole.MAGIC]: { value: 'magic', name: 'Magic', isPriveleged: false },
  [GroupRole.MAGICIAN]: { value: 'magician', name: 'Magician', isPriveleged: false },
  [GroupRole.MAJOR]: { value: 'major', name: 'Major', isPriveleged: false },
  [GroupRole.MAPLE]: { value: 'maple', name: 'Maple', isPriveleged: false },
  [GroupRole.MARSHAL]: { value: 'marshal', name: 'Marshal', isPriveleged: false },
  [GroupRole.MASTER]: { value: 'master', name: 'Master', isPriveleged: false },
  [GroupRole.MAXED]: { value: 'maxed', name: 'Maxed', isPriveleged: false },
  [GroupRole.MEDIATOR]: { value: 'mediator', name: 'Mediator', isPriveleged: false },
  [GroupRole.MEDIC]: { value: 'medic', name: 'Medic', isPriveleged: false },
  [GroupRole.MENTOR]: { value: 'mentor', name: 'Mentor', isPriveleged: false },
  [GroupRole.MEMBER]: { value: 'member', name: 'Member', isPriveleged: false },
  [GroupRole.MERCHANT]: { value: 'merchant', name: 'Merchant', isPriveleged: false },
  [GroupRole.MIND]: { value: 'mind', name: 'Mind', isPriveleged: false },
  [GroupRole.MINER]: { value: 'miner', name: 'Miner', isPriveleged: false },
  [GroupRole.MINION]: { value: 'minion', name: 'Minion', isPriveleged: false },
  [GroupRole.MISTHALINIAN]: { value: 'misthalinian', name: 'Misthalinian', isPriveleged: false },
  [GroupRole.MITHRIL]: { value: 'mithril', name: 'Mithril', isPriveleged: false },
  [GroupRole.MODERATOR]: { value: 'moderator', name: 'Moderator', isPriveleged: true },
  [GroupRole.MONARCH]: { value: 'monarch', name: 'Monarch', isPriveleged: false },
  [GroupRole.MORYTANIAN]: { value: 'morytanian', name: 'Morytanian', isPriveleged: false },
  [GroupRole.MYSTIC]: { value: 'mystic', name: 'Mystic', isPriveleged: false },
  [GroupRole.MYTH]: { value: 'myth', name: 'Myth', isPriveleged: false },
  [GroupRole.NATURAL]: { value: 'natural', name: 'Natural', isPriveleged: false },
  [GroupRole.NATURE]: { value: 'nature', name: 'Nature', isPriveleged: false },
  [GroupRole.NECROMANCER]: { value: 'necromancer', name: 'Necromancer', isPriveleged: false },
  [GroupRole.NINJA]: { value: 'ninja', name: 'Ninja', isPriveleged: false },
  [GroupRole.NOBLE]: { value: 'noble', name: 'Noble', isPriveleged: false },
  [GroupRole.NOVICE]: { value: 'novice', name: 'Novice', isPriveleged: false },
  [GroupRole.NURSE]: { value: 'nurse', name: 'Nurse', isPriveleged: false },
  [GroupRole.OAK]: { value: 'oak', name: 'Oak', isPriveleged: false },
  [GroupRole.OFFICER]: { value: 'officer', name: 'Officer', isPriveleged: false },
  [GroupRole.ONYX]: { value: 'onyx', name: 'Onyx', isPriveleged: false },
  [GroupRole.OPAL]: { value: 'opal', name: 'Opal', isPriveleged: false },
  [GroupRole.ORACLE]: { value: 'oracle', name: 'Oracle', isPriveleged: false },
  [GroupRole.ORANGE]: { value: 'orange', name: 'Orange', isPriveleged: false },
  [GroupRole.OWNER]: { value: 'owner', name: 'Owner', isPriveleged: true },
  [GroupRole.PAGE]: { value: 'page', name: 'Page', isPriveleged: false },
  [GroupRole.PALADIN]: { value: 'paladin', name: 'Paladin', isPriveleged: false },
  [GroupRole.PAWN]: { value: 'pawn', name: 'Pawn', isPriveleged: false },
  [GroupRole.PILGRIM]: { value: 'pilgrim', name: 'Pilgrim', isPriveleged: false },
  [GroupRole.PINE]: { value: 'pine', name: 'Pine', isPriveleged: false },
  [GroupRole.PINK]: { value: 'pink', name: 'Pink', isPriveleged: false },
  [GroupRole.PREFECT]: { value: 'prefect', name: 'Prefect', isPriveleged: false },
  [GroupRole.PRIEST]: { value: 'priest', name: 'Priest', isPriveleged: false },
  [GroupRole.PRIVATE]: { value: 'private', name: 'Private', isPriveleged: false },
  [GroupRole.PRODIGY]: { value: 'prodigy', name: 'Prodigy', isPriveleged: false },
  [GroupRole.PROSELYTE]: { value: 'proselyte', name: 'Proselyte', isPriveleged: false },
  [GroupRole.PROSPECTOR]: { value: 'prospector', name: 'Prospector', isPriveleged: false },
  [GroupRole.PROTECTOR]: { value: 'protector', name: 'Protector', isPriveleged: false },
  [GroupRole.PURE]: { value: 'pure', name: 'Pure', isPriveleged: false },
  [GroupRole.PURPLE]: { value: 'purple', name: 'Purple', isPriveleged: false },
  [GroupRole.PYROMANCER]: { value: 'pyromancer', name: 'Pyromancer', isPriveleged: false },
  [GroupRole.QUESTER]: { value: 'quester', name: 'Quester', isPriveleged: false },
  [GroupRole.RACER]: { value: 'racer', name: 'Racer', isPriveleged: false },
  [GroupRole.RAIDER]: { value: 'raider', name: 'Raider', isPriveleged: false },
  [GroupRole.RANGER]: { value: 'ranger', name: 'Ranger', isPriveleged: false },
  [GroupRole.RECORD_CHASER]: { value: 'record-chaser', name: 'Record-chaser', isPriveleged: false },
  [GroupRole.RECRUIT]: { value: 'recruit', name: 'Recruit', isPriveleged: false },
  [GroupRole.RECRUITER]: { value: 'recruiter', name: 'Recruiter', isPriveleged: false },
  [GroupRole.RED_TOPAZ]: { value: 'red topaz', name: 'Red Topaz', isPriveleged: false },
  [GroupRole.RED]: { value: 'red', name: 'Red', isPriveleged: false },
  [GroupRole.ROGUE]: { value: 'rogue', name: 'Rogue', isPriveleged: false },
  [GroupRole.RUBY]: { value: 'ruby', name: 'Ruby', isPriveleged: false },
  [GroupRole.RUNE]: { value: 'rune', name: 'Rune', isPriveleged: false },
  [GroupRole.RUNECRAFTER]: { value: 'runecrafter', name: 'Runecrafter', isPriveleged: false },
  [GroupRole.SAGE]: { value: 'sage', name: 'Sage', isPriveleged: false },
  [GroupRole.SAPPHIRE]: { value: 'sapphire', name: 'Sapphire', isPriveleged: false },
  [GroupRole.SARADOMINIST]: { value: 'saradominist', name: 'Saradominist', isPriveleged: false },
  [GroupRole.SAVIOUR]: { value: 'saviour', name: 'Saviour', isPriveleged: false },
  [GroupRole.SCAVENGER]: { value: 'scavenger', name: 'Scavenger', isPriveleged: false },
  [GroupRole.SCHOLAR]: { value: 'scholar', name: 'Scholar', isPriveleged: false },
  [GroupRole.SCOURGE]: { value: 'scourge', name: 'Scourge', isPriveleged: false },
  [GroupRole.SCOUT]: { value: 'scout', name: 'Scout', isPriveleged: false },
  [GroupRole.SCRIBE]: { value: 'scribe', name: 'Scribe', isPriveleged: false },
  [GroupRole.SEER]: { value: 'seer', name: 'Seer', isPriveleged: false },
  [GroupRole.SENATOR]: { value: 'senator', name: 'Senator', isPriveleged: false },
  [GroupRole.SENTRY]: { value: 'sentry', name: 'Sentry', isPriveleged: false },
  [GroupRole.SERENIST]: { value: 'serenist', name: 'Serenist', isPriveleged: false },
  [GroupRole.SERGEANT]: { value: 'sergeant', name: 'Sergeant', isPriveleged: false },
  [GroupRole.SHAMAN]: { value: 'shaman', name: 'Shaman', isPriveleged: false },
  [GroupRole.SHERIFF]: { value: 'sheriff', name: 'Sheriff', isPriveleged: false },
  [GroupRole.SHORT_GREEN_GUY]: { value: 'short green guy', name: 'Short Green Guy', isPriveleged: false },
  [GroupRole.SKILLER]: { value: 'skiller', name: 'Skiller', isPriveleged: false },
  [GroupRole.SKULLED]: { value: 'skulled', name: 'Skulled', isPriveleged: false },
  [GroupRole.SLAYER]: { value: 'slayer', name: 'Slayer', isPriveleged: false },
  [GroupRole.SMITER]: { value: 'smiter', name: 'Smiter', isPriveleged: false },
  [GroupRole.SMITH]: { value: 'smith', name: 'Smith', isPriveleged: false },
  [GroupRole.SMUGGLER]: { value: 'smuggler', name: 'Smuggler', isPriveleged: false },
  [GroupRole.SNIPER]: { value: 'sniper', name: 'Sniper', isPriveleged: false },
  [GroupRole.SOUL]: { value: 'soul', name: 'Soul', isPriveleged: false },
  [GroupRole.SPECIALIST]: { value: 'specialist', name: 'Specialist', isPriveleged: false },
  [GroupRole.SPEED_RUNNER]: { value: 'speed-runner', name: 'Speed-Runner', isPriveleged: false },
  [GroupRole.SPELLCASTER]: { value: 'spellcaster', name: 'Spellcaster', isPriveleged: false },
  [GroupRole.SQUIRE]: { value: 'squire', name: 'Squire', isPriveleged: false },
  [GroupRole.STAFF]: { value: 'staff', name: 'Staff', isPriveleged: false },
  [GroupRole.STEEL]: { value: 'steel', name: 'Steel', isPriveleged: false },
  [GroupRole.STRIDER]: { value: 'strider', name: 'Strider', isPriveleged: false },
  [GroupRole.STRIKER]: { value: 'striker', name: 'Striker', isPriveleged: false },
  [GroupRole.SUMMONER]: { value: 'summoner', name: 'Summoner', isPriveleged: false },
  [GroupRole.SUPERIOR]: { value: 'superior', name: 'Superior', isPriveleged: false },
  [GroupRole.SUPERVISOR]: { value: 'supervisor', name: 'Supervisor', isPriveleged: false },
  [GroupRole.TEACHER]: { value: 'teacher', name: 'Teacher', isPriveleged: false },
  [GroupRole.TEMPLAR]: { value: 'templar', name: 'Templar', isPriveleged: false },
  [GroupRole.THERAPIST]: { value: 'therapist', name: 'Therapist', isPriveleged: false },
  [GroupRole.THIEF]: { value: 'thief', name: 'Thief', isPriveleged: false },
  [GroupRole.TIRANNIAN]: { value: 'tirannian', name: 'Tirannian', isPriveleged: false },
  [GroupRole.TRIALIST]: { value: 'trialist', name: 'Trialist', isPriveleged: false },
  [GroupRole.TRICKSTER]: { value: 'trickster', name: 'Trickster', isPriveleged: false },
  [GroupRole.TZKAL]: { value: 'tzkal', name: 'TzKal', isPriveleged: false },
  [GroupRole.TZTOK]: { value: 'tztok', name: 'TzTok', isPriveleged: false },
  [GroupRole.UNHOLY]: { value: 'unholy', name: 'Unholy', isPriveleged: false },
  [GroupRole.VAGRANT]: { value: 'vagrant', name: 'Vagrant', isPriveleged: false },
  [GroupRole.VANGUARD]: { value: 'vanguard', name: 'Vanguard', isPriveleged: false },
  [GroupRole.WALKER]: { value: 'walker', name: 'Walker', isPriveleged: false },
  [GroupRole.WANDERER]: { value: 'wanderer', name: 'Wanderer', isPriveleged: false },
  [GroupRole.WARDEN]: { value: 'warden', name: 'Warden', isPriveleged: false },
  [GroupRole.WARLOCK]: { value: 'warlock', name: 'Warlock', isPriveleged: false },
  [GroupRole.WARRIOR]: { value: 'warrior', name: 'Warrior', isPriveleged: false },
  [GroupRole.WATER]: { value: 'water', name: 'Water', isPriveleged: false },
  [GroupRole.WILD]: { value: 'wild', name: 'Wild', isPriveleged: false },
  [GroupRole.WILLOW]: { value: 'willow', name: 'Willow', isPriveleged: false },
  [GroupRole.WILY]: { value: 'wily', name: 'Wily', isPriveleged: false },
  [GroupRole.WINTUMBER]: { value: 'wintumber', name: 'Wintumber', isPriveleged: false },
  [GroupRole.WITCH]: { value: 'witch', name: 'Witch', isPriveleged: false },
  [GroupRole.WIZARD]: { value: 'wizard', name: 'Wizard', isPriveleged: false },
  [GroupRole.WORKER]: { value: 'worker', name: 'Worker', isPriveleged: false },
  [GroupRole.WRATH]: { value: 'wrath', name: 'Wrath', isPriveleged: false },
  [GroupRole.XERICIAN]: { value: 'xerician', name: 'Xerician', isPriveleged: false },
  [GroupRole.YELLOW]: { value: 'yellow', name: 'Yellow', isPriveleged: false },
  [GroupRole.YEW]: { value: 'yew', name: 'Yew', isPriveleged: false },
  [GroupRole.ZAMORAKIAN]: { value: 'zamorakian', name: 'Zamorakian', isPriveleged: false },
  [GroupRole.ZAROSIAN]: { value: 'zarosian', name: 'Zarosian', isPriveleged: false },
  [GroupRole.ZEALOT]: { value: 'zealot', name: 'Zealot', isPriveleged: false },
  [GroupRole.ZENYTE]: { value: 'zenyte', name: 'Zenyte', isPriveleged: false }
};

const GROUP_ROLES = Object.values(GroupRole);

function findGroupRole(roleName: string): GroupRole | null {
  for (var [key, value] of Object.entries(GroupRoleProps)) {
    if (value.name.toUpperCase() === roleName.toUpperCase()) return key as GroupRole;
  }

  return null;
}

export { GroupRole, GroupRoleProps, GROUP_ROLES, findGroupRole };
