export enum JobType {
  ASSERT_PLAYER_TYPE = 'assert-player-type',
  CHECK_CREATION_SPAM = 'check-creation-spam',
  CHECK_INAPPROPRIATE_CONTENT = 'check-inappropriate-content',
  CHECK_PLAYER_BANNED = 'check-player-banned',
  CHECK_PLAYER_RANKED = 'check-player-ranked',
  INVALIDATE_DELTAS = 'invalidate-deltas',
  REVIEW_NAME_CHANGE = 'review-name-change',
  SCHEDULE_BANNED_PLAYER_CHECKS = 'schedule-banned-player-checks',
  SCHEDULE_COMPETITION_EVENTS = 'schedule-competition-events',
  SCHEDULE_COMPETITION_SCORE_UPDATES = 'schedule-competition-score-updates',
  SCHEDULE_FLAGGED_PLAYER_REVIEW = 'schedule-flagged-player-review',
  SCHEDULE_GROUP_SCORE_UPDATES = 'schedule-group-score-updates',
  SCHEDULE_NAME_CHANGE_REVIEWS = 'schedule-name-change-reviews',
  SCHEDULE_PATRON_GROUP_UPDATES = 'schedule-patron-group-updates',
  SCHEDULE_PATRON_PLAYER_UPDATES = 'schedule-patron-player-updates',
  SYNC_API_KEYS = 'sync-api-keys',
  SYNC_PATRONS = 'sync-patrons',
  SYNC_PLAYER_ACHIEVEMENTS = 'sync-player-achievements',
  SYNC_PLAYER_COMPETITION_PARTICIPATIONS = 'sync-player-competition-participations',
  SYNC_PLAYER_DELTAS = 'sync-player-deltas',
  SYNC_PLAYER_RECORDS = 'sync-player-records',
  UPDATE_COMPETITION_SCORE = 'update-competition-score',
  UPDATE_GROUP_SCORE = 'update-group-score',
  UPDATE_PLAYER = 'update-player',
  UPDATE_QUEUE_METRICS = 'update-queue-metrics'
}
