name: (App) Check Code Quality

on:
  pull_request:
    branches:
      - master
    paths:
      - "app/**"

jobs:
  lint:
    name: Run ESLint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.18.0

      - name: Install dependencies
        run: npm i

      - name: Run ESLint
        run: npm run lint
  type-check:
    name: Run Type Checking
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.17.0

      - name: Install dependencies
        run: npm i

      - name: Build app
        run: npm run build

      - name: Run tsc
        run: npx tsc
