name: (App) Production Deployment

on:
  push:
    branches:
      - master
    paths:
      - "app/**"

jobs:
  build-app-image:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.ORG_DOCKER_USERNAME }} -p ${{ secrets.ORG_DOCKER_PASSWORD }}

      - name: Build Docker Images and Push To Docker Hub
        run: |
          cd server
          docker build . -f Dockerfile -t wiseoldman/app:latest
          docker push wiseoldman/app
  deploy:
    name: Pull & Restart Docker Container
    needs: [build-app-image]
    runs-on: ubuntu-latest
    steps:
      - name: Restart docker
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USER }}
          passphrase: ${{ secrets.DO_SSH_PASS }}
          key: ${{ secrets.DO_SSH_KEY }}
          script: |
            cd wise-old-man
            docker image rm wiseoldman/app
            docker-compose pull app
            docker-compose up -d --no-deps --build app
            docker image prune
