name: Build Docs Image

on:
  push:
    branches:
      - master
    paths:
      - 'docs/**'

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.ORG_DOCKER_USERNAME }} -p ${{ secrets.ORG_DOCKER_PASSWORD }}

      - name: Build and Push To Docker Hub
        run: |
          cd docs
          docker build . --file Dockerfile --tag wiseoldman/docs:latest
          docker push wiseoldman/docs:latest
  deploy:
    runs-on: ubuntu-latest
    needs: [build-docs]
    steps:
      - name: Restart docker
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USER }}
          passphrase: ${{ secrets.DO_SSH_PASS }}
          key: ${{ secrets.DO_SSH_KEY }}
          script: |
            cd wise-old-man
            docker-compose pull
            docker-compose up --build -d
