name: Build League API Image

on:
  push:
    branches:
      - league/shattered-relics
    paths:
      - "server/**"

jobs:
  build-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.ORG_DOCKER_USERNAME }} -p ${{ secrets.ORG_DOCKER_PASSWORD }}

      - name: Build and Push To Docker Hub
        run: |
          cd server
          docker build . --file Dockerfile --tag wiseoldman/league-api:latest
          docker push wiseoldman/league-api:latest
  deploy:
    runs-on: ubuntu-latest
    needs: [build-api]
    steps:
      - name: Restart docker
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USER }}
          passphrase: ${{ secrets.DO_SSH_PASS }}
          key: ${{ secrets.DO_SSH_KEY }}
          script: |
            cd wise-old-man
            docker-compose pull league-api
            docker-compose up -d --no-deps --build league-api
