name: (Docs) Publish API Documentation

on:
  push:
    branches:
      - master
    paths:
      - "docs/**"
      - ".github/workflows/docs-test.yml"
      - ".github/workflows/docs-publish.yml"

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3

      - name: Install dependencies
        run: cd docs && npm ci

      - name: Build website
        run: cd docs && npm run build

      - name: Publish to Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build
          user_name: "Psikoi"
          user_email: "ruben.amendoeira@gmail.com"
