name: (League API) Check Code Quality

on:
  pull_request:
    branches:
      - league/trailblazer-reloaded
    paths:
      - "server/**"

jobs:
  lint:
    name: Run ESLint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.16.0

      - name: Install dependencies
        run: npm i

      - name: Run ESLint
        run: npm run lint
