name: Check API Code Quality

on:
  pull_request:
    branches:
      - release/v1
    paths:
      - "server/**"

jobs:
  lint-server:
    name: ESLint (Server)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache node modules
        uses: actions/cache@v1
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install global dependencies
        run: npm i
      - name: Install server dependencies
        run: |
          cd server
          npm i
      - name: Run ESLint (Server)
        run: |
          cd server
          npm run lint
